id: P54E3FE44
initial_creation_type: input
source_metadata:
  title: Empowerment Series
  language: bo
  description: 'Various writings on the subject of empowerment or initiation (abhiṣeka;
    dbang bskur), including rites for conferment (dbang chog):'
  volume:
    479a388e237e4690837d6cd02c40a831:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Prayers
    0a2eef2563164e4f92965a47647b71a3:
      title: 'Shower of Indestructible Splendour: A Self-Initiation for the Guru Practice
        of the Vidyādhara Assembly, from the Heart-Essence of the Vast Expanse'
      parent: Rites
    5c32cd4efd6b4298867ceb91a7e73a35:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Rites
    02901e95d73b4c8fb2320288aa477484:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Rites
    72297fbc10a8466285bc0fb0bb991ee3:
      title: 'Illuminating the Meaning of Empowerment: A Self-Initiation for the Female
        Practice of the Ḍākinī'
      parent: Rites
    2d3a9e2c2f2f4875b2b632805fe7fe13:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Rites
created_at: '2022-03-01T03:39:26.959906'
last_modified_at: '2022-03-01T03:39:26.959909'
